version: '3'

services:
  db:
    image: mysql:8
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: webapi
    container_name: webapi
    build: .
    command: ./wait-for-it.sh db:3306 -- python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
    networks:
      - mynetwork

volumes:
  db_data:

networks:
  mynetwork:
